[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sim2spec"
version = "0.1.1"
description = "GPU ND-LArTPC sim-to-analysis workflow wrapper around DUNE/larnd-sim with QA + profiling."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "pyyaml>=6.0",
  "h5py>=3.9",
  "numpy>=1.23",
  "pandas>=2.0",
  "matplotlib>=3.7",
  "fire>=0.5",
  "cupy-cuda12x"
]

[project.scripts]
sim2spec = "cli:main"

[tool.setuptools]
py-modules = ["cli", "config_patch", "prof", "provenance", "qa", "runner", "utils"]

[tool.setuptools.package-dir]
"" = "src"
